### ISSUE TITLE
Far more compact view

### ISSUE THREAD

**Issue by anonimuos** [stnkl/EverythingToolbar#12]
Two things I would like about this toolbar in the future:

1. A hotkey to directly focus inside its text box
2. A more compact results view like Everything has, not this list with huge icons and fonts - as small spacing as its own context menu

**Comment by profucius** [comment]
I second the request of both, but especially number 2.

Also I propose a third request here, since it relates to view. Allow for the search popup to auto-resize itself to the top of the screen (if enough results to do so). I use a 55" 4K screen as my monitor, and the little search box only takes up maybe 20% of my screen. I would rather just open Everything.app itself for the amount of data I can see at once. Thank you.

**Comment by stnkl** [comment]
The next release will have customizable item templates:

![image](https://user-images.githubusercontent.com/17520641/98443083-60f4a480-2109-11eb-9640-67099b4e137f.png)

**Comment by anonimuos** [comment]
Instead of Win+Alt+S, can you make the hotkey customizable, please? :) Allow the user to set one of this choice?

**Comment by anonimuos** [comment]
Compact view and hotkey work great as of 0.6.0.0.
