### ISSUE TITLE
Integrate filter in search input

### ISSUE THREAD

**Issue by billie-spektor** [stnkl/EverythingToolbar#127]
Thanks for making this tool! 

Would it be possible to integrate the filters in the search input? Just like you can type "audio:[search string]" in Everything and only search for audio files. 

This way it's possible to immediately use a search filter, without having to manually switch to the filter.

**Comment by billie-spektor** [comment]
Some additional info: I thought this was built-in functionality of filters in Everything, but it only seems to work if I add a macro when editing the filter in Everything.

**Comment by Horst12** [comment]
Filters are built-in of Everything GUI and stored in a CSV file.
But the SDK which is used by the Toolbar to access Everything does not support the filter sysntax.

**Comment by stnkl** [comment]
@Horst12 is correct. The SDK currently does not support that. The only alternative would be to write out every file ending like `ext:aac;flac;wav;mp3 ...` instead of `audio:` directly into the search box which of course is not handy at all. Maybe the upcoming SDK for Everything 1.5 will have better macro support.

Closing for now.
