### ISSUE TITLE
Toolbar doesn't show up in taskbar context menu

### ISSUE THREAD

**Issue by dr-baba** [stnkl/EverythingToolbar#139]
I am unable to get the toolbar from the context menu. I have tried multiple times, multiple versions etc. I have the latest version of Everything and .NET Framework. Is there a way to add the toolbar manually using 'New Toolbar'?

![image](https://user-images.githubusercontent.com/50979846/114405984-be6daf80-9bd9-11eb-8765-eea38395fa70.png)

**Comment by stnkl** [comment]
- Did you install [EverythingToolbar](https://github.com/stnkl/EverythingToolbar/releases) as well as [Everything](https://www.voidtools.com) (two separate applications)? Other users have made that mistake before.
- Did you open the context menu twice after installing EverythingToolbar? It will always look like your screenshot the first time you open it but it shows up after opening it again.

There is no way to add the toolbar via the "New toolbar" menu entry.

**Comment by dr-baba** [comment]
Yes I have both installed and I have tried to open the context menu multiple times.
![image](https://user-images.githubusercontent.com/50979846/114408949-84ea7380-9bdc-11eb-96ec-0ee2b8189502.png)

**Comment by stnkl** [comment]
Okay, could you please do me a favor and uninstall this version of EverythingToolbar and try an older version which had the old installer?

For that please follow these steps:
1. Uninstall the currently installed version of EverythingToolbar
2. Either reboot your computer or restart Windows Explorer via the task manager
3. Download version 0.6.2-beta2 from [here](https://github.com/stnkl/EverythingToolbar/releases/tag/0.6.2-beta2)
4. Extract it somewhere and navigate into that folder
5. Right click the install.cmd and select "run as administrator"
6. If the console window that opens doesn't show any error messages you can just close it (otherwise post a screenshot here please)
7. Open the task bar context menu twice and see if EverythingToolbar is showing up

In case you want to uninstall this version just run the uninstall.cmd as administrator.

**Comment by dr-baba** [comment]
I uninstalled as you said and installed the older version. The console showed no error but it still isn't showing up on the taskbar context menu unfortunately.

**Comment by sfksuperman** [comment]
Installed the v0.6.3 and same thing is happening to me. In Toolbars > Everything Toolbar is ticked but not seen on taskbar anywhere.

**Comment by stnkl** [comment]
> Installed the v0.6.3 and same thing is happening to me. In Toolbars > Everything Toolbar is ticked but not seen on taskbar anywhere.

This is not exactly the same problem though as this issue is about EverythingToolbar not showing up in the toolbars menu at all. Please make sure to check again if it is really not there. Users have missed it before as it appears as a small magnifiying glass on the right side at first.
![image](https://user-images.githubusercontent.com/17520641/114861650-d289fa80-9ded-11eb-97d6-6e5806b0bb38.png)

> I uninstalled as you said and installed the older version. The console showed no error but it still isn't showing up on the taskbar context menu unfortunately.

That is really weird. Unfortunately I am quite busy currently and can't look into it. I will get back to this in a few weeks. Sorry about that.

**Comment by dr-baba** [comment]
No worries, thanks for the help.

**Comment by sfksuperman** [comment]
Found it after restart or something but it's not working when searching any
file. Also, it cannot be dragged to the left or right side of the taskbar.
[image: image.png]

**Comment by stnkl** [comment]
> Found it after restart or something but it's not working when searching any file. Also, it cannot be dragged to the left or right side of the taskbar. [image: image.png]

Please have a look at #133 and #123.

**Comment by sfksuperman** [comment]
Hi,

Thanks for the help. Much appreciated. It's working like a charm.

**Comment by sfksuperman** [comment]
Can you please reduce the font size of the placeholder "Search with
Everything"?

**Comment by stnkl** [comment]
> Can you please reduce the font size of the placeholder "Search with Everything"? 

This will be part of #147.

**Comment by sfksuperman** [comment]
You want to say that it's a suggested feature which will be taken care of
soon?

**Comment by stnkl** [comment]
> You want to say that it's a suggested feature which will be taken care of soon?

I won't give any ETA but it will be possible at some point.

**Comment by sfksuperman** [comment]
Ok sure. Thanks for the app. It's awesome. I will be looking at it's
upcoming build.

**Comment by stnkl** [comment]
@dr-baba Just to update you on this: I have been thinking more about why this could happen but I am honestly rather clueless. If you are still interested in solving this problem could you maybe check if the registry entries are correct after installation? This is what it should look like (other than different version numbers): https://github.com/stnkl/EverythingToolbar/issues/120#issuecomment-782838755 I honestly don't expect this to be the problem but you never know.

**Comment by dr-baba** [comment]
Here's the registry.

Is it supposed to be in Program Files or in User/Local like from that thread?

![image](https://user-images.githubusercontent.com/50979846/121697740-ec9b3d00-caff-11eb-8e26-a6334f5f7b13.png)

**Comment by stnkl** [comment]
Registry looks fine. The msi-installer installs to C:\Program Files (x86)\EverythingToolbar by default. But wether it shows in the context menu or not should not even be affected by whether the program files exist.

My only guess is that - since your system seems to be slightly modified/themed - there have been other system changes that could have an impact on this. But I really can't diagnose that unfortunately.

**Comment by sfksuperman** [comment]
Hi again,

How to do the same thing in windows 11 now?

Regards,
Md Shah Faishal Khan
Contact: +918791950903

**Comment by stnkl** [comment]
@sfksuperman Windows 11 is not supported yet. See #178.

**Comment by sfksuperman** [comment]
Oh no! It was awesome in window 10. Anytime soon you make it compatible with windows 11 also?

**Comment by Horst12** [comment]
After installing StartAllback
I have installed the Toolbar using the manual method in Windows 11.
It runs fine as before in Windows 10.

**Comment by stnkl** [comment]
@dr-baba In another issue I saw you got EverythingToolbar working in Windows 11. Since this issue really seems to be specific to your particular (former?) Windows installation I will close this issue for now.
