### ISSUE TITLE
[Feature request]  Use the space to preview the file

### ISSUE THREAD

**Issue by Grergo** [stnkl/EverythingToolbar#61]
#### Hope to support QuickLook, use  space  to preview the file.

**Comment by Horst12** [comment]
There is no QuickLook necessary as Everything itself does support Explorer Preview
and also do file manager replacements like Total Commander.

**Comment by Keagel** [comment]
> There is no QuickLook necessary as Everything itself does support Explorer Preview
> and also do file manager replacements like Total Commander.

Everything itself supports previews within their own window, not within the search results of `EverythingToolbar`, unless I'm missing something.

**Comment by jacksongoode** [comment]
Second this!

**Comment by stnkl** [comment]
I just tried this and it works pretty well. But due to the fact that the search box is always focused <kbd>Space</kbd> can not be used for opening the preview. Instead for now I decided to use <kbd>Alt</kbd>+<kbd>Space</kbd>.

At some point I might change it to just <kbd>Space</kbd> but a few other changes are needed to allow the search box to lose focus without closing the popup.

Let me know if you have any suggestions on when exactly the search box should unfocus to allow pressing <kbd>Space</kbd> to open the preview.

**Comment by Horst12** [comment]
Alt-Space will collide with Microsofts PowerToys Run feature.
