### ISSUE TITLE
[Feature Request] Add option to default to EverythingToolbar instead of native search

### ISSUE THREAD

**Issue by oSumAtrIX** [stnkl/EverythingToolbar#63]
An option to replace the search popup window when typing on the keyboard inside the start menu with EverythingToolbar would enhance the seamless integration into windows and ease using EverythingToolbar instantly by skipping the shortcut

**Comment by Horst12** [comment]
What would be the benefit compared to the Toolbar in the taskbar as its now.
Now you can just put the cursor in the Toolbar field and start typing.
There is no faster way to get to this.

**Comment by stnkl** [comment]
I actually really like this idea. However I can imagine the implementation being really hacky which I'm really not a fan of. Definitely something to look into though!

**Comment by Chillstice** [comment]
I prefer to hide the 'search with Cortana' eyesore since it's an inefficient use of the taskbar and I have muscle memory of hitting the windows key and typing to search. I can't be the only one that does this - so overriding the native search would be highly appreciated. 

For the last few years I've been using Wox so I can hit alt+space and start typing to search with Everything, but replacing the native windows search would be a more elegant solution.

**Comment by krlvm** [comment]
I think this could be done in [this](https://github.com/krlvm/BeautySearch) way, but it would require some additional reverse-engineering.

**Comment by dan1994** [comment]
> I prefer to hide the 'search with Cortana' eyesore since it's an inefficient use of the taskbar and I have muscle memory of hitting the windows key and typing to search.

+1!

My main issue here is that I have to use my mouse, which is no fun (for me!). If you could add a keybinding for opening search I could get used to it (not necessarily override `win` or `win+s`).

**Comment by Horst12** [comment]
> 
> 
> > I prefer to hide the 'search with Cortana' eyesore since it's an inefficient use of the taskbar and I have muscle memory of hitting the windows key and typing to search.
> 
> +1!
> 
> My main issue here is that I have to use my mouse, which is no fun (for me!). If you could add a keybinding for opening search I could get used to it (not necessarily override `win` or `win+s`).

But you have already an hotkey for the toolbar which you also can change.
After pressing the hotkey you can start typing your search.
What is missing here ?

**Comment by dan1994** [comment]
I actually looked for that and didn't find it. My bad!
As a side note: I see the default is `win+shift+s` which is already bound to snip & sketch (for everyone I think). Might be worth changing...

**Comment by Horst12** [comment]
> 
> 
> I actually looked for that and didn't find it. My bad!
> As a side note: I see the default is `win+shift+s` which is already bound to snip & sketch (for everyone I think). Might be worth changing...

The default is Win + Alt + S
Thats no collision with any Windows function.

**Comment by stnkl** [comment]
> I think this could be done in [this](https://github.com/krlvm/BeautySearch#manual-installation) way - CortanaApp object can be called from JS code and somehow access native APIs (that's how a browser window opens from the Bing search results), but it would require some additional reverse-engineering.

This is a really interesting application!

So the goal of this issue is to search with EverythingToolbar instead of Windows/Cortana. For that I see two different options:
1. Integrate EverythingToolbar into the existing Windows search window (which is _not_ the start menu!)
2. Trigger EverythingToolbar whenever the start menu is open and the user starts typing (use a keyboard hook)

Option 1 would require a lot of reverse engineering and significant changes to EverythingToolbar which I don't think is worth it.
The only problem I see with option 2 would be in cases like for @Chillstice where they want to hide any indication of search (search button or search box) completely. In that case it would be counterintuitive to call EverythingToolbar a toolbar and probably cause a lot of confusion.

**Comment by dan1994** [comment]
> > 
> > 
> > I actually looked for that and didn't find it. My bad!
> > As a side note: I see the default is `win+shift+s` which is already bound to snip & sketch (for everyone I think). Might be worth changing...
> 
> The default is Win + Alt + S
> Thats no collision with any Windows function.

My bad again! Sorry for the misinformation.

**Comment by krlvm** [comment]
> > I think this could be done in [this](https://github.com/krlvm/BeautySearch#manual-installation) way - CortanaApp object can be called from JS code and somehow access native APIs (that's how a browser window opens from the Bing search results), but it would require some additional reverse-engineering.
> 
> This is a really interesting application!
> 
> So the goal of this issue is to search with EverythingToolbar instead of Windows/Cortana. For that I see two different options:
> 
> 1. Integrate EverythingToolbar into the existing Windows search window (which is _not_ the start menu!)
> 2. Trigger EverythingToolbar whenever the start menu is open and the user starts typing (use a keyboard hook)
> 
> Option 1 would require a lot of reverse engineering and significant changes to EverythingToolbar which I don't think is worth it.
> The only problem I see with option 2 would be in cases like for @Chillstice where they want to hide any indication of search (search button or search box) completely. In that case it would be counterintuitive to call EverythingToolbar a toolbar and probably cause a lot of confusion.

I don't think there's a reason to integrate the app into the search window, but I believe it's possible to inject JS code which will launch the app instead the same way the search window executes commands (type `taskkill /f /im explorer.exe` and it will work).
I used "Microsoft Edge DevTools (Preview)" from Microsoft Store (it's important) to write this application.

**Comment by ruvaldak** [comment]
Simply having WinKey place the cursor in the search box to allow typing should be enough. Seems EverythingToolbar is placed over top of the windows menu, Basically:
WinKey is pressed
Win menu is opened
Everything search box is activated
Can interact with Win menu and ignore Everything as the search results only appear when typing begins
Can immediately begin typing

Would probably have to find a way to have it ignore any form of win+ shortcuts. Should probably be fine to have have it check for WinKey released, and ignore WinKey released if another key is pressed. Something to that effect. Bit hackey but should work perfectly fine as a temporary measure. I'm no professional though.

**Comment by stnkl** [comment]
I created a dirty AutoHotkey script to hijack Windows start menu search and redirect it to EverythingToolbar:

```autohotkey
#NoEnv
#SingleInstance, Force
#UseHook On
SendMode Input
SetWorkingDir, %A_ScriptDir%
SetTitleMatchMode, 3

StartMenuWindowName := "Search"
if A_Args.Length() > 0
{
    StartMenuWindowName := A_Args[1]
}

TriggerEverythingToolbar()
{
    BlockInput, On
    lastKey = %A_ThisHotkey%
    Send, {Esc}
    WinWaitNotActive, %StartMenuWindowName%
    Send, #!s
    Sleep, 1
    Send, %lastKey%
    BlockInput, Off
}

Hotkey, IfWinActive, %StartMenuWindowName%
Characters := "!#$%&'()*+,-./0123456789:;<=>?@_abcdefghijklmnopqrstuvwxyz{}|\`"
Loop, Parse, Characters
{
    Hotkey, %A_LoopField%, TriggerEverythingToolbar
}
```

[HijackSearch.zip](https://github.com/stnkl/EverythingToolbar/files/5920669/HijackSearch.zip)

If your Windows installation is not in English you have to start it with the start menu window name as a launch parameter. For example for German you would start it with `HijackSearch.exe Suche`. The easiest way is to create a shortcut of HijackSearch.exe and change the target property. You can find the start menu window name in the task manager:

![image](https://user-images.githubusercontent.com/17520641/106792718-cdbf0280-6656-11eb-945a-e91b8770083b.png)

It is recommended to run the script as admin because otherwise some lines of code don't work (`BlockInput, On/Off`) which prevents keypresses from reaching unwanted applications when typing quickly.

I am no AutoHotkey expert and really didn't do a lot of testing. This might not work on older versions of Windows (Windows 10 20H2 here). I am sure this can be done better and more reliably but I still wanted to share.

**Comment by ruvaldak** [comment]
Just tried your ahk script @stnkl, works perfectly. Good job on that. Obviously a very hacky way of doing it but it gets the job done quite well.

**Comment by ziplock9000** [comment]
Actually, rather than replace, I'd like to have both searches. Maybe in different tabs or all in the same list or something?

**Comment by stnkl** [comment]
I implemented the autohotkey script in EverythingToolbar. It works quite well for me but I expect it to be problematic for some people. Especially those that are not using a recent version of Windows 10 (and I won't be able to support old versions of Windows myself). Therefore I marked the feature as experimental. 

After enabling the option when typing into the start menu it automatically redirects the input to EverythingToolbar. You can prevent that by holding down <kbd>Alt</kbd> or <kbd>Ctrl</kbd>.

Unfortunately I couldn't find a way to distinguish between the native search app or the start menu being in focus so it will circumvent search app input as well (if not holding down one of the mentioned keys when entering the first search letter). Let me know if anybody knows a way to distinguish between start menu and search app (both give focus to `SearchApp.exe`). 

It will be available for testing in the beta coming later this week.
