### ISSUE TITLE
Suggestion on keyboard shortcuts.

### ISSUE THREAD

**Issue by StillForever** [stnkl/EverythingToolbar#81]
I have some suggestions for reference only.
ctrl + n  ctrl + p   substitute   ↓  ↑  
ctrl + return   open path
hold alt double click   open properties

**Comment by stnkl** [comment]
Search results can be opened with a single click in EverythingToolbar. To be more in line with that I would suggest using single click rather than double click:

| Shortcut                                     | Function    |
|------------------------------------------------|------------------|
| <kbd>Shift</kbd>+<kbd>Return</kbd>| Open in Everything     |
|<kbd>Shift</kbd>+<kbd>Click</kbd>|Open in Everything|
|<kbd>Ctrl</kbd>+<kbd>Return</kbd>|Open path|
|<kbd>Ctrl</kbd>+<kbd>Click</kbd>|Open path|
| <kbd>Alt</kbd>+<kbd>Return</kbd> | Properties    |
| <kbd>Alt</kbd>+<kbd>Click</kbd> | Properties|

What do you think?

Is <kbd>Ctrl</kbd>+<kbd>n</kbd>/<kbd>p</kbd> used in other applications? I haven't seen those before.

**Comment by StillForever** [comment]
I think it's not bad .
This idea is derived from emacs.

**Comment by stnkl** [comment]
Unfortunately <kbd>Alt</kbd>+<kbd>Return</kbd> is not possible as it is already used by the taskbar to open its settings. <kbd>Alt</kbd>+<kbd>Click</kbd> works however. It will be available in the next release.

I decided against implementing <kbd>Ctrl</kbd>+<kbd>n</kbd>/<kbd>p</kbd> because it is very specific to emacs users and can easily be done with [AutoHotkey](https://www.autohotkey.com) if needed.
